### PR TITLE
Feature/k8s

### PR DESCRIPTION
**Pull request by raphaelcervantes**
Added database, logger, and grafana. I did not provision grafana with a database to keep the example simpler.

### CODE REVIEW

**Comment by laroque** [comment]
Thanks Raphael, I'm going to pull this in but want to try and actually run it before the merge. The silence is not a lack of interest.

**Comment by laroque** [comment]
Thanks Raphael, these are very useful. I'm changing the base branch of the merge because I'd like to make some changes before it goes into develop (largely expanding the prose doc, but also changing a few names and filling in a few more pieces), but given the effort you've already put in I think it makes sense for me to make those rather than asking you to do them.

**Comment by raphaelcervantes** [comment]
Ok. I have all the passwords for rabbitmq, grafana, and postgresql stored as a secret on my own setup. I also have a datasource provisioned for grafana in case you want to put that in this mesh.

**Comment by laroque** [comment]
I've done most of it but if you've already got the datasource secret details figured out could you send me the manifest for that (or send another PR to this branch)?

**Comment by raphaelcervantes** [comment]
### grafana-values.yaml     

```
# plugins: 
#   devopsprodigy-kubegraf-app
admin:
  user: admx
  existingSecret: grafana-admin
#ingress:
#  enabled: True
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/use-regex: "true"
#  hosts:
#    - name: nlwymmd.orpheus
#      paths: ["/grafana/?(.*)"]
datasources:
  secretName: orpheusdb-grafana
metrics:
  enabled: true
#config:
#  useGrafanaIniFile: true
#  grafanaIniConfigMap: grafana-ini-config
persistence:
  enabled: false
```

### grafana-postgres-secret.yaml 
```

apiVersion: v1
kind: Secret
metadata:
  name: orpheusdb-grafana
  namespace: default
type: Opaque
stringData:
  other_datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: sensor_db
        type: postgres
        url: postgres-kvstore-postgresql.default.svc.cluster.local
        database: sensor_data
        user: user
        secureJsonData:
          password: "password"
        jsonData:
          sslmode: "disable" # disable/require/verify-ca/verify-full
          maxOpenConns: 0         # Grafana v5.4+
          maxIdleConns: 2         # Grafana v5.4+
          connMaxLifetime: 14400  # Grafana v5.4+
          postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false

```

**Comment by laroque** [comment]
Great, thanks

**Pull request merged**
