### PR TITLE
Feature/k8s

### PR DESCRIPTION
**Pull request by raphaelcervantes**
Added a k8s example.

### CODE REVIEW

**Comment by laroque** [comment]
Thanks @raphaelcervantes this is really helpful. A few (I hope small/easy) requests:
1. Could you rename the folder from `examples/k8s` to `examples/second-mesh`? I expect that there will be more k8s related examples in the future. Also please rename the source file to `source/second-mesh.rst`
2. Ideally the example would include a values file for rabbitmq and a corresponding secret. I don't know if you already have these, if so please add; if not, I'll merge this PR and then plan to add that whenever I expand the prose.

**Comment by raphaelcervantes** [comment]
@laroque made requested changes.

**Comment by raphaelcervantes** [comment]
I don't have a secret setup for rabbitmq. I'll leave it to you if that's desired. I just have it in plain text in a release file.

**Comment by laroque** [comment]
Thanks @raphaelcervantes this is a great starting version

**Review by laroque — APPROVED** [review]

**Pull request merged**
