### PR TITLE
Feature/second mesh

### PR DESCRIPTION
**Pull request by laroque**
@raphaelcervantes here is my expanded version built on what you provided. It converts the prose portion of the guide to proper sphinx syntax and makes all of the names generic. Thanks for all the work on the technical pieces. You're not in driplineorg, so you can do an official review, but it would be great if you'd take a look at this PR and let us know what you think.

@nsoblath an official review would also be good. This has both prose docs and a complete second-mesh example for running in k8s. I ran all the pieces tonight in the k8s cluster that ships with docker for desktop (nice to see that that mode works easily).

### CODE REVIEW

**Comment by raphaelcervantes** [comment]
Hi Ben,
1. Is `blank.values.yaml` the standard name format? Why is it better than` blank-values.yaml`? I'm wondering if I need to start using that standard.

2. https://github.com/driplineorg/controls-guide/blob/feature/second-mesh/examples/second-mesh/key-value-store.values.yaml#L5
I think `"rabbitmq-app.default.svc.cluster.local" `should change to `"rabbitmq.default.svc.cluster.local"`

3. https://github.com/driplineorg/controls-guide/blob/feature/second-mesh/source/guides/second-mesh.rst
Some of the code blocks and markdown didn't render well for me.

4.
>  This tutorial is being written and tested using kubernetes 1.15.5 as shipped with docker desktop CE (2.2.0.5) on MacOS. It is not expected to be very sensitive to those versions, but check the release notes if you differ widely or have issues.

I developed this helm charts with kubernetes version 1.17. And they still work with version 1.18.2

5. https://github.com/driplineorg/controls-guide/blob/feature/second-mesh/source/guides/second-mesh.rst#visualization

> looking at our daata. 

typo. daata-> data.

**Comment by laroque** [comment]
Thanks for those, I'll take care of them before the merge:

1. `blank.values.yaml` isn't "better" than `blank-values.yaml` for any particular reason. I wanted to make it easier to visually split the "name" part from the label parts, and to make it easy to see which yaml files are helm release values and which are k8s manifests. I think this was more clear but am open to something else. You certainly don't need to change what you're doing elsewhere, but you can use this pattern if it is useful to you.
2. I agree by eye, not sure how it worked as is. I'll re-test and make sure it works before I merge.
3. The file is technically ReST (restructured text), which is what sphinx uses to compile to helm (also pdf, epub, and others). Github renders the markdown-equivalent parts, but doesn't know how to render some of the more sophisticated directives/features (I notice cross-references and literal include blocks in particular)
4. Thanks, I quoted what I was testing against because I wasn't sure what you're running. I'll update to reflect your system as the dev system and mine as "tested on"
5. Wump... thanks

**Comment by laroque** [comment]
@nsoblath I've fixed Raphael's comments and also some errors found while re-testing. I think this is ready for your review (it would be great if you could do a full integration test reproducing things. It should be very easy with docker for mac.

**Review by wsmithpnnl — COMMENTED** [review]
Made some minor updates to the tutorial documentation.

**Pull request merged**
